project_id = "wxdapfuirtkgpbtpeopn"

[functions.intelipost-proxy]
verify_jwt = false

[functions.intelipost-audit]
enabled = true
verify_jwt = true
import_map = "./functions/intelipost-audit/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/intelipost-audit/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/intelipost-audit/*.html" ]

[functions.sync-magento-orders]
enabled = true
verify_jwt = true
import_map = "./functions/sync-magento-orders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-magento-orders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-magento-orders/*.html" ]

[functions.get-order-details]
enabled = true
verify_jwt = true
import_map = "./functions/get-order-details/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-order-details/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-order-details/*.html" ]
